# Generated by Django 4.1.6 on 2023-02-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entrerpise',
            field=models.ManyToManyField(blank=True, null=True, related_name='entreprises', to='reclapp.entreprise'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='reclapp.client'),
        ),
    ]
